[package]
name = "paging"
version = "4.0.2"
publish = ["patina-fw"]
edition = "2021"
license = "BSD-2-Clause-Patent"
description = "Paging library for AArch64 & X64 architectures"
repository = "https://github.com/OpenDevicePartnership/paging"
keywords = ["paging"]

[package.metadata.docs.rs]
features = ["doc"]

[dependencies]
bitfield-struct = "0.10"
bitflags = "2.6.0"
log = { version = "^0.4", default-features = false }
cfg-if = "1.0.0"

[features]
doc = []
