[package]
name = "paging"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause-Patent"
description = "Paging library for AArch64 & X64 architectures"
repository = "https://github.com/pop-project/paging"
keywords = ["paging"]

[package.metadata.docs.rs]
features = ["doc"]

[dependencies]
bitfield-struct = "0.9.2"
bitflags = "2.6.0"

[features]
std = []
doc = []
